### ISSUE TITLE
Missing support for DB prefix

### ISSUE THREAD

**Issue by sduif** [SpotlerSoftware/magento2-mailplus-connector#9] opened 2018-07-19 08:10 UTC
The module seems to be missing support for databases that use a DB prefix. Upon installing the module the database tables are created, but are missing the prefix.

**Example:**

- Prefix: **magento_**
- **php bin/magento setup:upgrade**
- Tables created: **mp_catalog_rule_updated_at** / **mp_quote_conversion**
- Missing prefix **magento_**

**Magento 2.2.4**

The issue only became apparent for us in Magento 2.2.4 since Magento's core fix for https://github.com/magento/magento2/issues/8035 was included. This in turn fixed the module's use of extension_attributes.xml. Resulting in errors while sending transaction emails: 

`Base table or view not found: 1146 Table 'my_db.magento_mp_quote_conversion' doesn't exist`

**Temporary fix**

I fixed this by commenting the corresponding lines in **extension_attributes.xml**, but of course this hinders some of the module's functionality.

**Comment by fvschie** [comment] 2018-07-25 08:07
This issue was caused by directly using table names, instead of asking the dbms for the correct table name.

This was fixed in a migration step in 23ac292d71157529ee1b19612f8b7cc5a4e30771 for the Magento 2.1.* branch and commit 445b03004b75e8009becf7f4c81e135e18cc72e3 for the Magento >2.2.*

**Closed** 2018-07-25 08:08 UTC
